### PR TITLE
device: fix device descriptors URL

### PR DESCRIPTION
**Pull request by alexandear**
This PR changes `deviceDescriptorsURL` in the `device/gen.go` file because https://raw.githubusercontent.com/puppeteer/puppeteer/main/src/common/DeviceDescriptors.ts does not exist anymore.

~The latest version of device descriptions is https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/Device.ts. But, when I run `go generate` with `const deviceDescriptorsURL = "https://raw.githubusercontent.com/puppeteer/puppeteer/main/packages/puppeteer-core/src/common/Device.ts"` got `error: could not find start`. Looks like the file format was changed in the [commit 87c08fd](https://github.com/puppeteer/puppeteer/commit/87c08fd86a79b63308ad8d46c5f7acd1927505f8). So, I left the link to the latest valid [commit f42336](https://github.com/puppeteer/puppeteer/blob/f42336cf83982332829ca7e14ee48d8676e11545/packages/puppeteer-core/src/common/DeviceDescriptors.ts).~

### CODE REVIEW

**Comment by alexandear** [comment]
@ZekeLu looks like chromedp has flaky tests. Could you take a look at why tests are failing?

**Comment by ZekeLu** [comment]
Hi @alexandear, thanks for the pull request!

Here is the failure:

```
testing.go:1090: TempDir RemoveAll cleanup: unlinkat /home/runner/work/_temp/TestRemoteAllocatorNoModifyURL281325479/001/Default: directory not empty
```

The issue is tracked by #1105. I don't know how to fix this issue. We can ignore it as of now.

**Comment by ZekeLu** [comment]
> got `error: could not find start`

The fix is easy. So I think it's better to fix it. Can you please copy the change from https://github.com/ZekeLu/chromedp/commit/1ad03d8cfaecbed2cfbd01b4475e83e517289340 to your pull request?

**Comment by alexandear** [comment]
> The fix is easy. So I think it's better to fix it. Can you please copy the change from https://github.com/ZekeLu/chromedp/commit/1ad03d8cfaecbed2cfbd01b4475e83e517289340 to your pull request?

@ZekeLu done

**Pull request merged**
