### PR TITLE
Use %ProgramFiles% and %LocalAppData% to locate chrome.exe more critically

### PR DESCRIPTION
**Pull request by szzhiyang**
Because `Program Files` folder and `Program Files (x86)` folder are not always under C: drive, 
and `Local` folder is not always under `%UserProfile%\AppData`.

### CODE REVIEW

**Comment by szzhiyang** [comment]
@mvdan 

Hi, I've added fall-back paths with `C:\` and `%UserProfile%`.

According to [documentation](https://golang.org/pkg/path/filepath/#Join), the result of `filepath.Join` is always [**Cleaned**](https://golang.org/pkg/path/filepath/#Clean), which does not contain extra slash on the right.

**Comment by mvdan** [comment]
Sorry, but I didn't mean duplicating the entries. For each one of those, you check the var version if the var is defined, otherwise you check the older hard-coded path we have in master.

**Comment by mvdan** [comment]
Also, I know that filepath.Join cleans. But `Join(foo, "bar")` is still simpler than `Join(foo, "/bar")`

**Comment by ZekeLu** [comment]
In my opinion, `findExecPath` makes a best-effort to find the browser. It does not have to cover all cases. The users can always use `chromedp.ExecPath` to specify the path if `findExecPath` does not work. Closing.

**Pull request closed without merging**
