### PR TITLE
fix: AttributesAll possible resource leak

### PR DESCRIPTION
**Pull request by hypocenter**

### CODE REVIEW

**Comment by mvdan** [comment]
Sorry, but this isn't enough information. The commit message must explain what the leak is, and why your commit is fixing it.

**Comment by hypocenter** [comment]
'defer' node.RUnlock() calls inside the loop don’t get executed until the func ends , not when each step of for loop ends. All calls here will eat up the func’s stack and may cause unforeseen problems.

**Comment by mvdan** [comment]
You don't have to tell me; you have to specify that in the commit message.

**Comment by mvdan** [comment]
Sorry, I don't know why you closed this. In any case, I'll just commit straight to master.

**Pull request closed without merging**
