### PR TITLE
Add allocator option: IgnoreCertErrors

### PR DESCRIPTION
**Pull request by shelld3v**

### CODE REVIEW

**Comment by ZekeLu** [comment]
Thanks for the contribution!

There are lots of command line options for the Chrome browser ([a non-official and a little outdated list](https://peter.sh/experiments/chromium-command-line-switches/)). I'm not sure whether this one is special enough to get a name. And if we want to give it a name, I think `IgnoreCertErrors` looks more accurate.

**Comment by ZekeLu** [comment]
It turns out that this option is useful (I used it several times when using a proxy to capture the network traffics), and the cited web page does not include this option, so I'm going to merge this PR.

**Comment by shelld3v** [comment]
@ZekeLu: It turns out that this option is useful, so I'm going to merge this PR
Also @ZekeLu: *closed #809*

**Comment by ZekeLu** [comment]
Sorry for making you confuse. I want to move this option after `ProxyServer` and modify the comment, so I can't merge this PR directly. This PR is closed after the cherrypick. You can find the contribution in the commit history. Thank you!

**Pull request closed without merging**
