### PR TITLE
replace "interface{}" with "any"

### PR DESCRIPTION
**Pull request by alexandear**
This PR replaces `interface{}` with `any` by running the command:
```
gofmt -w -r 'interface{} -> any' .
```

`any` appears in [Go 1.18](https://tip.golang.org/doc/go1.18#language).

### CODE REVIEW

**Comment by kenshaw** [comment]
@alexandear I do appreciate what you're doing here, but this change makes it non-backwards compatible in general without really gaining anything other than a syntax change. Myself, I'm not a fan of backwards compatibility, but this seems like a superficial change that create hassles for users who may be stuck using a older version of Go. I know there are a number of different orgs, who for a number of different reasons, are stuck on Go 1.16 (or on even older versions of Go). This would force them to upgrade their entire Go toolchain to at least Go 1.18, which suffice to say, may not be possible due to compatibility with other packages/libs, or for any number of other reasons (political or otherwise).

That said, I'd be happy to consider integrating this kind of a change later this year after 1.21 or 1.22 next year, after Go 1.18+ has been out for a bit longer. It's worth noting that Go 1.17 received an update as recently as a few months ago, and is still being supported by the Go team.

**Comment by alexandear** [comment]
@kenshaw thank you for the detailed explanation. `chromedp` already can't be compiled with go < 1.18. This explicitly states in the [release notes](https://github.com/chromedp/chromedp/releases/tag/v0.8.8).

Also, I tried to compile `chromedp` with go 1.17:
```
go1.17 build
# github.com/chromedp/chromedp
./eval.go:81:19: undefined: reflect.Pointer
./eval.go:84:9: undefined: reflect.Pointer
```

So, that's why I made the PR.

**Comment by kenshaw** [comment]
@alexandear I must have missed when this change happened. I've pushed a commit, and tagged it, reenabling support for Go 1.16.

**Comment by ZekeLu** [comment]
My bad. I used `reflect.Pointer` without realizing that it is only available since go 1.18.

**Comment by kenshaw** [comment]
@ZekeLu not your fault. They changed the name from `reflect.Ptr` to `reflect.Pointer` in `go1.18`. I have no idea why. To be honest, looking at that code, I'm pretty sure I can rewrite it without relying on a specific reference to `reflect.Ptr`, but I don't have the time at the moment to bother. The fix I pushed earlier today is more than adequate for now.

**Comment by alexandear** [comment]
`reflect.Ptr` still exists in [Go 1.20](https://pkg.go.dev/reflect#pkg-constants). It's defined as `const Ptr = Pointer`

**Pull request closed without merging**
