### PR TITLE
Fixes Possible Memory Leak Issue Using Pool

### LINKED ISSUE #134: Possible Memory Leak Issue Using Pool
My program crawls the web using chromedp.Pool for quite some time and the memory usage grows horribly and won't subside. My instincts is that the many channels used in the TargetHandler are used without calling close() anywhere. Is any body else experiencing the same issue? Will get to dig deeper whenever I've got the time.

### PR DESCRIPTION
**Pull request by carusyte**
this PR is supposed to fix #134 issue

### CODE REVIEW

**Comment by korovkinand** [comment]
Your fix to pool shutdown causes deadlock. Shutdown func locks mutex "p.rw.Lock()" and then calls Release. This function immediately tries to reacquire mutex
Removing lock at the beginning of Shutdown fix problem

**Comment by carusyte** [comment]
@korovkinand I'm replying as soon as I read your message, but I'm not quite certain about the deadlock issue you said, cause it seems that I'm not getting stuck anywhere by a deadlock, and I'm like spawning  ten's of thousand's of *Res and calling *Res.Release() after usage, before calling a single *Pool.Shutdown(). One thing to note is that I haven't pulled and merged that latest trunk master yet, not sure if you're using a different merged version than mine. I'll investigate further as soon as I've got the time. I'm kind of busy right now.

**Comment by kenshaw** [comment]
Please rebase this code off master, and collapse to a single commit. It's not possible to merge this without considerable effort.

**Comment by kenshaw** [comment]
For what it's worth -- I appreciate the work that's been done here. I would just like to mention though that `chromedp` has some upcoming / massive changes that will be pushed soon:

1. Package name will change to some project name under the github.com/chromedp/ namespace. For the high-level package, I'm not sure yet what it'll be called. This is being done so that `cdp` and `chromedp-gen` can sit separately from this main code, as the `chromedp` package should be independent of both of those projects
2. Converting to proper interfaces in cdp package. While this should be fairly straightforward, quite a bit of renaming of the func's / types will be done in the main chromedp package. This is more so that the `cdp` package and the `chromedp-gen` can be used independently of the main repository. 
3. Some high-level / breaking API changes on the `Pool` type and other runners.
4. Move to proper versioning strategy (this is also driving the splitting of the repository). 

I expect to finish this work before the end of the year, and will merge to master as soon as it's done. You can see some of the progress / the ideas I've been working on, on an older branch that I pushed to github.com/kenshaw/chromedp -- please note that's just a working / scratch repository, and is about 2 months out-dated at this point.

**Comment by korovkinand** [comment]
@carusyte I have my own fork and copied your fix there. My fork is synced with master. Also, I moved up Shutdown call in Release, cause it makes no effect if context was canceled and connection to instance was closed. 
You can look at my fork. Sorry for late answer, I accidentally turned off notifications.

**Comment by korovkinand** [comment]
I can't understand how you don't get deadlock. Shutdown calls "p.rw.Lock()" and then "r.Release()", Release calls "r.p.rw.Lock()", so tries to reacquire the same mutex. Here deadlock happens. Shutdown releases mutex only after closing using defer.

**Comment by carusyte** [comment]
@kenshaw Sorry Ken, I've few experiences in using git and collaborating in github and I was rather confused by `merging` and `rebasing`. Didn't mean to bring you any inconvenience. I'll rectify this PR as soon as I fully understand what `rebasing` really is and how to do it, hopefully before you push that big revamping!

**Comment by kenshaw** [comment]
It's not a problem; it's just that I'm not likely to have time to fix and test this implementation on my own, if it's not easy to merge it.

Here's some hints for working with Git and rebase:

```sh
# checkout git repository
$ cd $GOPATH/src/github.com/knq/ && git clone https://github.com/knq/chromedp.git

# add your remote
$ git remote add carusyte https://github.com/carusyte/chromedp.git
$ git fetch carusyte

# checkout the branch for this PR
$ git checkout -b myfix carusyte/myfix

# rebase off master
$ git rebase origin/master

# git will fail here, if there's a conflict
# edit the files, and fix whatever conflicts exist
# after a conflict has been fixed in a file, do:
$ git add <file-that-has-been-fixed>
# then continue the rebase
$ git rebase --continue

# after all conflicts have been resolved, and the rebase has finished:
$ git rebase -i
# you want to "squash" all the commits into a single commit. you do that by changing 'pick' to 'fixup'

# after you've rebased it into a single commit, do a force push of the branch to your repository:
$ git push -f carusyte myfix
```

**Comment by carusyte** [comment]
@kenshaw many thanks for the ready-to-use command hints! I think I can grasp some of the "rebasing" spirit now after I finished the job. But it wound up a little bit weird that all the commit history is gone now, and all "meld down" into your last commit, maybe I'd have leave one of the commit to be "pick"...  Some of the commits were merged from other developers' branch, I might be accidentally erasing their contribution too... 

If that's not right, I can rebase again and definitely not in a hurry next time.

**Comment by kenshaw** [comment]
I would just suggest to collapse commits from the same author. The issue is that it's difficult for me to commit the time to review all of the commits independently. However reviewing 1 or 3 commits in total is completely doable. Also, from what I've reviewed so far, I don't believe this would work as expected.

**Comment by carusyte** [comment]
@kenshaw I've redone a rebase by going through each difference rather than just conflicting segments this time, and now it seems to be working normally in my application. I assume it was due to an incorrect auto-merge of difference by opendiff the last time I carried out the rebase.

I hope this PR could be qualified for an effective fix. Would you mind pointing out the specific part that is failing to work as expected?

**Comment by kenshaw** [comment]
@carusyte I appreciate you updating this. I'll review soon.

**Comment by kenshaw** [comment]
@carusyte for what it's worth, I believe many of the conflicts have been due to modifying auto-generated files (ie, `cdp/cdp.go`). The proper way to submit a change to this file would be to update the respective template in the `cmd/chromedp-gen` tool.

**Comment by carusyte** [comment]
@kenshaw wow...that really adds an extra dimension of complexity. 
However, I guess I've managed to locate the template file (extra.qtpl) and get it updated accordingly. I didn't test it by running the gen tool though, praying for mercy...

**Comment by kenshaw** [comment]
This is my #1 priority to fix now that I've finished splitting up the repository. The `chromedp-gen` command has been moved to github.com/chromedp/chromedp-gen . Please note that it has significantly changed. If you'd like to recreate this PR there, please feel free. Apologies for causing the extra work -- I really appreciate how everyone involved here has positively contributed to the project!

**Comment by carusyte** [comment]
@kenshaw Although it causes some headache for me, I'm glad to see this project is vigorously being improved here. I do believe evolution entails some painful process... 
I've made a new rebase to keep up with your revamping, and it seems working normally in my application...I hope I'm doing this right.

**Comment by kenshaw** [comment]
The changes that were made was just splitting up the project, and inverting the `cdp/cdputil` control so that it's the highest level package at `cdproto`. Appreciate the consolidation; the next changes are the real "big" changes, as the about ... 50% of the internal "guts" will be ripped out and replaced (the API will more or less stay intact).

**Pull request closed without merging**
